### ISSUE TITLE
Sorting by votes does not work

### ISSUE THREAD

**Issue by alivannikov** [segler-alex/radiobrowser-api-rust#22] opened 2019-12-16 09:22 UTC
Old API supported ordering, but this functionality seems to be broken in new API. Please compare results of these 2 requests:

http://www.radio-browser.info/webservice/json/stations/search?order=votes&reverse=true&limit=50&country=russia

https://nl1.api.radio-browser.info/json/stations/search?order=votes&reverse=true&limit=50&country=russia

**Comment by alivannikov** [comment] 2019-12-17 10:41
@segler-alex Or is the issue that new/old apis use different DB instances and all the votes were lost during DB migration? So basically all of them are around "0" at the moment. Is it possible to transfer "votes" information from old DB then? Otherwise it will take quite a long time until radio stations will get properly prioritised again by accumulating votes.

**Comment by segler-alex** [comment] 2019-12-17 19:40
vote numbers and click numbers are not synchronized. this feature is not planed. i have no good solution to provide a reliable number without a serious amount of extra syncing yet.

voting and clicking counts are not very reliable
https://www.gkbrk.com/wiki/gamingradiobrowservotes/

so i did not find it necessary to invest too much time. if somebody has an idea how to fix the problem of multivotes, and -clicks, please feel free to suggest and help with it.

for the time beeing every server instance has its own counting of votes and clicks

**Comment by segler-alex** [comment] 2019-12-17 19:43
i really am in need of a smart way of counting clicks :)

but maybe this is even bad in itsself, i am not sure yet, if i even should count the clicks, because it suffers from the "rich get richer" symptom. what do you think about this thought?

**Comment by segler-alex** [comment] 2019-12-17 20:02
i want give people the oportunity to find new types of music, they might like.

maybe it is not a good idea to have a centralized voting with a single value in the end. 
could it be possible to have a more decentralized approach to expressing preferences.

**Comment by alivannikov** [comment] 2019-12-18 10:42
> i want give people the oportunity to find new types of music, they might like.
> 
> maybe it is not a good idea to have a centralized voting with a single value in the end.
> could it be possible to have a more decentralized approach to expressing preferences.

I think the fact that API may be used by many different radio apps by many different people already making voting decentralised. Personally I find notion of popularity very useful. There are literally thousands radio stations nowadays, and probably up to hundred per particular country. It is becoming hard to find good content without popularity sorting. When testing new api I clearly see degradation of radio stations quality, because list starts with some random stations nobody heard about. I agree, this is useful for discovering new recently added radio stations, but this is not most common use case.

**Comment by segler-alex** [comment] 2019-12-18 10:56
you are right, i think it will getget better when apps, start using all servers. then they all will get their votes and clicks. different ones of course, but it will happen. clicks are only kept 30 days. 

syncing all servers clicks is still a hard thing to do, to get a correct number

**Comment by cztomsik** [comment] 2019-12-18 19:36
maybe adding option to sort by `id` might improve this it a bit (good stations stay for a while and that means lower `id`)

or being able to sort by both `id` & `votes`?

**Comment by segler-alex** [comment] 2020-01-06 22:31
i managed to make sync faster, i will try in a future release to sync click numbers

**Comment by segler-alex** [comment] 2020-01-11 20:14
i have some questions:
1) how do you think, votes and click counts are different?
2) should clicks/votes stay forever?
3) are votes or clickes better suited to express how well the stations are liked?
4) do we need both?
5) if clicks/votes stay forever, would you keep the events that increased it also forever, to recount it at any time again?
these are serious questions for me, they go arround in my brain for quite some time now... i really would like to have another opinion.

**Comment by s-n-g** [comment] 2020-01-11 23:44
1. Votes are one per user/client. I don't know how this cannot be abused (record listener ip on the server? save a listener id on the client? Would any of these be possible?

Clicks are how many times a station has been played, which in our case here may mean how many times a "Playable station URL" has been requested. This is easy to count at the server side but can also be abused

2. If recorded, yes

3. I'd say clicks

4. probably not

5. I don't really understand what you mean here, sorry...

By "abuse" I mean writing a script/command and execute it say every x minutes/hours/days hitting a station's vote / click url

**Comment by segler-alex** [comment] 2020-01-12 11:27
**ON keeping forever:**

what if a station at some point was a very good station, then after 5 years it changes but has already more clicks/votes than anybody else, others will maybe never increase enough. and the current value does not reflect what people think of it.

**Comment by s-n-g** [comment] 2020-01-12 12:38
This can only be addressed by downvoting.

And clicks, if kept forever, will stop being increased while other stations' clicks will, so eventually, they will have a higher value.

Then again we can have voting kept forever (with downvoting available) and clicks resetting every month, which come to think of it, makes more sense. This way we can have votes indicating the long-run quality of the station and clicks indicating the short-run. What do you think about that?

Or have no clicks counted at all, but keep forever-votes and last-month-votes.

I don't know... It is a puzzle...

**Comment by segler-alex** [comment] 2020-01-12 13:40
**the current sitution**
* votes are increased forever, it is just a single value -> i don't like it
* every single click is kept with timeinformation in the database, clicks older than 30 days are removed, clickcount of each station is updated with adding all clicks together every hour. this should give a very accurate number of clicks -> i like to keep it, can also be mirrored to other servers, which i already implemented in version 0.6.2

**Comment by segler-alex** [comment] 2020-01-12 13:43
single clicks kept in the database do amount to over 1.000.000 rows but it is managable

**Comment by s-n-g** [comment] 2020-01-12 18:22
What exactly about voting is it that you do not like?
Is it voting as a context? would you rather remove it altogether?
Is it that it's just a single value?
Or that it is not mirrored to other servers?

**Comment by segler-alex** [comment] 2020-01-12 18:32
the thing that bothers me most is that i am unable to mirror a single value by nature consistently to other servers, where changes can occur in both directions.

but a value that always gets up and never down again is also something that seems not right to me... it is like never forgetting what happened, even when it is 100 years ago (ok seems unlikely for this project :)

**Comment by segler-alex** [comment] 2020-01-12 18:35
i had an idea today, that somehow redefines what votes mean:

in the future there might be a way for clients to store their favourites list of stations on the server, so that they can sync it over multiple devices, apps, ...
and the votes would just be the sum of the station's occurences in all favourites lists.
to clean the system over time, lists that do net get updated or read from clients would get deleted after 1 month

how do you like that idea?

**Comment by segler-alex** [comment] 2020-01-12 18:37
i do NOT mean a login for the server, that is what i absolutely do not want. i want to keep it open without login to use.

but maybe if an app wants to use this server storage, it could just generate its own id, and use it as a key for storage. this would be completely anonymous.

**Comment by s-n-g** [comment] 2020-01-12 19:15
The whole concept of voting is exactly never forgetting what happened, even when it is 100 years ago, IMHO

Isn't there downvoting available? If there is one, the value of votes can go down as well

About the server-side favorite list of stations: You mean that each app developer could create an **app-id** and "upload" a list of stations on the server using **it**? That would be interesting, but it wouldn't work as a voting system: the developer of the app might choose to load his server-side favorite list at startup, so you always get it read by clients, even if not used

To make it clear, my current implementation (which sadly still uses the old API), will automatically present 100 stations sorted by vote. Then the user can use this list as is, or perform a search to get his customized list

I hope you do not mean using a **client-id**; this would raise anonymity concerns by the users

**Comment by cztomsik** [comment] 2020-01-12 19:16
How about syncing [Weighted_arithmetic_mean](https://en.wikipedia.org/wiki/Weighted_arithmetic_mean)?

I mean, instead of syncing how many clicks there have been on each server, you could sync popularity, relative to the total number of votes. That could be synced easily I think (you can make average from all servers, again using total number (or popularity of the server) as a scale.

There are probably some edge cases but it could be huge simplification of the problem - but OFC I have no idea how that could work out.

**Comment by segler-alex** [comment] 2020-01-12 19:27
@s-n-g the new api is mostly the same as the new api. most of the time only the link to it is different.
there are 2 things you have to check: always use stationuuid instead of id, and get a server link by dns check, but i wrote a simple example for that http://www.radio-browser.info/gui/#!/api

**Comment by segler-alex** [comment] 2020-01-12 19:28
@cztomsik could you elaborate in more detail what you mean with popularity? do you mean munching votes and clicks together?

**Comment by cztomsik** [comment] 2020-01-12 20:47
TBH I'm not very familiar with the current api/intended design (I just wanted some list of radios, sorted by popularity and I've found this project, I've tried to use the new api and then I've found there's no votes so I'm using the old one)

But if it was my project, I'd do this:
1. hide radio `url` behind redirect
2. use redirect to track number of `plays`
3. use number of `plays` to compute `local_popularity` (when compared to the `total_plays` of all radios on this server) - so if the given server is new and empty, first played station would be most popular, etc.
5. sync this `local_popularity` together with total number of plays on this server, so every server can compute `overall_popularity` from its `local_popularity` + all what was synced from others, but it would be weighted by respective server's `total_plays` (new server -> almost no effect, old server -> a lot of effect)

Like in real world - when you get recommendation from somebody you know, you weight it more than if it's from somebody unknown.

**Comment by segler-alex** [comment] 2020-01-12 21:12
@cztomsik thank you, very interesting idea. one question: you said you were searching for votes, but you could also use the clicks, which do work since today on the new api. would that fit your need?

**Comment by cztomsik** [comment] 2020-01-12 21:41
@segler-alex no idea, I'll try it when get back to the project but I think it was empty too (maybe just wrong server?) I was trying rock & pop so I guess there should be something.

**Comment by segler-alex** [comment] 2020-01-12 21:44
@cztomsik if it is still empty, please tell me the exact request you did

**Comment by alivannikov** [comment] 2020-01-13 09:10
@segler-alex Do you plan to migrate votes from old API or do you plan to start from scratch? I think it may take quite a long time to accumulate votes so that it will reflect real situation. Personally for me currently it will be even more useful just to copy current values rather than having upvote/downvote functionality. I think values accumulated so far will reflect real situation for very long time (years?).

I do not see any problem in "votes staying forever". I can't image what should happen to station so that previous votes are not valid somehow. Except the case when it is completely closed. But then last check will fail and station will not be "active" at all, so it is not a problem.

**Comment by segler-alex** [comment] 2020-01-14 00:08
@alivannikov there would be two possibilities for votes.
1. do sync votes to second level servers only once, then let them each increase votes on their own without any future synchronization.
2. do a regular sync to second level servers, override any changes of votes, people have made.
what do you like more? do you have other ideas?

**Comment by alivannikov** [comment] 2020-01-14 11:01
@segler-alex Not sure what are second level servers? Are those servers used by old api? If old api meant to be depricated anyway, and eventually all the API consumers should switch to new api and new servers for voting - I guess option 1 is ok.

**Comment by segler-alex** [comment] 2020-01-14 21:36
it is described at http://www.radio-browser.info/gui/#!/faq

there is only one main server at the moment, which is the old server and it has the old api.
the second level servers are 4 at the moment and are currently only mirroring the main server. they have the new api.

in the future the second level servers will also sync to each other, so you can make changes anywhere and it will distribute through the network.

at some point the main server will get killed and the now second level servers will become the main servers.

**Comment by alivannikov** [comment] 2020-01-15 09:08
@segler-alex I see, so every server has own database with own votes counters? Why not just using dedicated DB instance used by all api servers?

**Comment by segler-alex** [comment] 2020-01-15 19:26
@alivannikov  yes every server has it's own database. this is by design, i always wanted to be as open as possible, more open than any radio api out there. this means for me, that not only me should be able to setup servers but also everyone else, it should also be very simple to do and make mirroring and extending data easy. if i would design a (centralized) system with a single database, it would meat the requirement of distributing requests, but it would not meet the requirement of having really independent instances. also one database means also a single point of failure. a single point that can be attacked... i think of this project more as email not as facebook. i want to have a network, where no single point is more important than another. if somebody out there wants to sponsor a server they can set them up themselves and tell me the address. also if you have a very extreme usecase with a lot of requests, you can even setup a caching server easily on your own infrastructure. if you a sponsor of a server gets trusted by the community i add them to the dns name, so people can find them more easily and start pulling from them. (like it works for linux-distribution downloads) but it should also be possible to have their own network. long thing short: it is NOT a bug, its a feature! :)

**Comment by s-n-g** [comment] 2020-01-15 22:05
All this is great, but imho all servers should be fully synced as frequently as possible.

By fully, I mean all provided data (clicks, votes, whatever)

This will provide a "common" experience to all clients no matter what mirror they connect to.

Imagine connecting to server 1 and havin 45 votes for station A and 32 votes for station B.
Then imagine the same client connecting to server 2 (due to activating a vpn service for example), having 39 votes for station A and 58 for station B.

Wouldn't that be confusing?
Both for the user and the station owner?

**Comment by segler-alex** [comment] 2020-01-19 12:28
i understand you, still there is no good technical solution yet.
i implemented a simple sync, which does basically work. BUT! it may drop some votes.
This is because of how it works:
-> on every pull, check if the other servers station has a higher votes number
-> if higher then overwrite the votes number of the local server with the higher number

this may drop votes that happened on the local server
but for now it is the best i can think of and the votes field is used again.

feel free to comment and suggest better solutions.

**Comment by segler-alex** [comment] 2020-02-01 15:59
closing this, because nobody complained

**Closed by segler-alex** 2020-02-01 15:59 UTC
Labels: enhancement, help wanted, question
